manifest:
    remotes:
        - name: zmkfirmware
          url-base: https://github.com/zmkfirmware
        - name: nickconway
          url-base: https://github.com/nickconway
        - name: amgskobo
          url-base: https://github.com/amgskobo
    projects:
        - name: zmk
          remote: nickconway
          revision: dev
          import: app/west.yml
        - name: zmk-keyboard-rollow
          remote: nickconway
          revision: main
          path: extra-modules/rollow
          import: config/west.yml
        - name: zmk-keyboard-toucan
          remote: nickconway
          revision: dynamic-macro-rec-indicator
          path: extra-modules/toucan
          import: config/west.yml
        - name: zmk-input-inertia
          remote: nickconway
          revision: include-fix
          path: extra-modules/inertia
    self:
        path: config
